runtime: python311

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  FLASK_ENV: production

entrypoint: gunicorn --bind :$PORT app:app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto